[build-system]
# Minimum requirements for the build system to execute.
requires = ["cython", "numpy", "setuptools", "wheel"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
src_paths = ["raster_tools", "test"]
