name: rstools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - affine
  - build
  - cfgrib
  - dask<=2024.2.1
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - netcdf4
  - numba
  - numpy
  - odc-geo
  - pandas
  - pre-commit
  - pyarrow
  - pyogrio
  - pyproj
  - pytest
  - pytest-mock
  - pytest-xdist
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2
  - twine
  - xarray
