name: rstools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - affine
  - cython
  - dask
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - numba
  - numpy
  - pandas
  - pip
  - pre-commit
  - pygeos
  - pyproj
  - rioxarray
  - scipy
  - xarray
  - pip:
    - nose2
