name: Tests
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{matrix.os }} - ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env:
          - requirements/39-ci.yml
          - requirements/310-ci.yml
          - requirements/311-ci.yml

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Log Environment
        run: |
          python -V
          conda info
          conda list

      - name: Test ${{ matrix.env }}
        run: |
          pytest -v -n 2
