name: Tests
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-vresion }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements/default.txt
      - name: Test with pytest
        run: |
          pytest
